PATCH  http://localhost:8081/api/posts/1
Content-Type: application/json

{
    "title": "Patch example",
    "content": "Esto es un nuevo post editado",
    "image": "asasddsa",
    "category": "other"
}
